---
title: "Data Science Certification Committee (DSSC)"
---

The DSSC oversees the entire certification process, makes all decisions about certification, and provides constructive feedback to applicants who are not approved.

## Composition

The DSSC consists of distinguished certified (or formerly certified, now retired) members of the ASA who are broadly representative of the membership. Members serve staggered three-year terms. DSSC members are appointed by the President-Elect or the Executive Director according to the usual committee appointment practices of the ASA. The chair of the committee is also appointed by the appropriate President-Elect or Executive Director to serve a three-year term, again in accordance with the ASA's usual processes.

## Responsibilities

The DSSC:

- Sets its own procedures for reviewing applications
- Makes recommendations to the Board of Directors regarding changes to the certification process
- Assists in the planning and provision of services to certified members
